version: "2"
linters:
  default: all
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
